# <center>CS 4660 Lab 1</center>

#### <div align = "right">Hiroko Itagaki    (CIN: 305064830) </div>


#### 1. Import the numpy package with the alias np

In [45]:
import numpy as np

#### 2. Create a vector of zeros of size 10 but the fifth value which is 1 

In [46]:
vector = np.zeros(10, dtype=int)
vector[4] = 1
print(vector)

[0 0 0 0 1 0 0 0 0 0]


#### 3. Create a 3 X 3 array of any values. Add a column of ones to the end

In [47]:
a = np.arange(9).reshape((3,3))
a[:, -1:] = 1
print(a)

[[0 1 1]
 [3 4 1]
 [6 7 1]]


#### 4. Create a vector with values ranging from 10 to 49 

In [48]:
vector2 = np.arange(10, 50)
print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Reverse the above vector (first element becomes last)

In [49]:
print(vector2[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6. Create a 4x4 matrix with values ranging from 0 to 15 

In [50]:
vector3 = np.arange(16).reshape((4,4))
print(vector3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Create a 3x3x3 array with random values 

In [51]:
d = np.floor(100 * np.random.random((3,3,3))).astype(int)
print(d)

[[[55 73 82]
  [47 97 36]
  [49  3 27]]

 [[17 33 26]
  [42 73 36]
  [ 6 60  4]]

 [[31 64 98]
  [55 32 28]
  [56 20 74]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [52]:
array = np.floor(100 * np.random.random((10,10))).astype(int)
print('array: \n', array)

print ('\n')

print('Minimum value : ', array.min())
print('Maximum value: ', array.max())

array: 
 [[25 83 88 45 65 55 34 96 82 34]
 [75 99 28 29  2 66 46 60 60 69]
 [40 74 94 82 62 30 98  4 88  5]
 [62 23 51 53 81 41  6  1 99 57]
 [ 0 44  9 18 20 16 23 93 95  7]
 [32 62 64 14 21 55 51 31  9 54]
 [94 73 12 76  9  9  7  1 73 45]
 [75 88 84 26 11 64 73 85 42 97]
 [45 33 63 90 48 61 27 30 13 99]
 [19 24 72 57  8 18 76 24 20 30]]


Minimum value :  0
Maximum value:  99


#### 9. Create a random vector of size 30 and find the mean value 

In [53]:
vector4 = np.floor(100 * np.random.random((30))).astype(int)
print('Vector 4: \n', vector4)

print ('\n')

print('Mean value :', np.mean(e))

Vector 4: 
 [82 29  0 41 74 65 84 21 54 52 86 14 69 75 52 38 27 98 84 66 17 15 91 37 19
 31 80 24 27 51]


Mean value : 47.4666666667


#### 10. What does NaN mean? Submit in a comment

NaN means "Not a number", and it is a float value. 

NaN is not equal to 0.

It is used when the result cannot be expressed as a number.

ex) print(float("inf")-float("inf")) 


#### 11. Write a function that takes 1D array and negates all elements which are between 3 and 8, in place. Demo it with an array of your choosing

In [59]:
# Negate elements between 3 and 8 on array
def negates(array):
    array[(array >= 3) & (array <= 8)] *= -1


array_1D = np.floor(10 * np.random.random((30))).astype(int)
    
print(array_1D)
negates(array_1D)
print(array_1D)

[7 9 1 7 6 3 9 1 1 6 4 3 9 1 7 1 5 7 0 6 7 6 5 2 8 6 8 9 5 3]
[-7  9  1 -7 -6 -3  9  1  1 -6 -4 -3  9  1 -7  1 -5 -7  0 -6 -7 -6 -5  2 -8
 -6 -8  9 -5 -3]
